// File generated by FlutterFire CLI.
// Firebase project credentials configured for production
// Project ID: smart-home-iot-5ef3e

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWsNL0M372W1Q9LRMK4l1hOqZ4c42SjLY',
    appId: '1:54102103552:web:smartHomeWebApp',
    messagingSenderId: '54102103552',
    projectId: 'smart-home-iot-5ef3e',
    authDomain: 'smart-home-iot-5ef3e.firebaseapp.com',
    storageBucket: 'smart-home-iot-5ef3e.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWsNL0M372W1Q9LRMK4l1hOqZ4c42SjLY',
    appId: '1:54102103552:android:9b38496d2b561b73e12ae5',
    messagingSenderId: '54102103552',
    projectId: 'smart-home-iot-5ef3e',
    authDomain: 'smart-home-iot-5ef3e.firebaseapp.com',
    storageBucket: 'smart-home-iot-5ef3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWsNL0M372W1Q9LRMK4l1hOqZ4c42SjLY',
    appId: '1:54102103552:ios:smartHomeIOSApp',
    messagingSenderId: '54102103552',
    projectId: 'smart-home-iot-5ef3e',
    authDomain: 'smart-home-iot-5ef3e.firebaseapp.com',
    storageBucket: 'smart-home-iot-5ef3e.firebasestorage.app',
    iosBundleId: 'com.example.asFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWsNL0M372W1Q9LRMK4l1hOqZ4c42SjLY',
    appId: '1:54102103552:macos:smartHomeMacOSApp',
    messagingSenderId: '54102103552',
    projectId: 'smart-home-iot-5ef3e',
    authDomain: 'smart-home-iot-5ef3e.firebaseapp.com',
    storageBucket: 'smart-home-iot-5ef3e.firebasestorage.app',
    iosBundleId: 'com.example.asFlutterProject',
  );
}
